// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/main/proto/contactsapi/customfieldschema.proto

package contactsapi_customfield

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateCustomFieldRequest_Type int32

const (
	CreateCustomFieldRequest_TEXT         CreateCustomFieldRequest_Type = 0
	CreateCustomFieldRequest_NUMBER       CreateCustomFieldRequest_Type = 1
	CreateCustomFieldRequest_BOOLEAN      CreateCustomFieldRequest_Type = 2
	CreateCustomFieldRequest_DATE_TIME    CreateCustomFieldRequest_Type = 3
	CreateCustomFieldRequest_EMAIL        CreateCustomFieldRequest_Type = 4
	CreateCustomFieldRequest_PHONE_NUMBER CreateCustomFieldRequest_Type = 5
	CreateCustomFieldRequest_URL          CreateCustomFieldRequest_Type = 6
)

var CreateCustomFieldRequest_Type_name = map[int32]string{
	0: "TEXT",
	1: "NUMBER",
	2: "BOOLEAN",
	3: "DATE_TIME",
	4: "EMAIL",
	5: "PHONE_NUMBER",
	6: "URL",
}
var CreateCustomFieldRequest_Type_value = map[string]int32{
	"TEXT":         0,
	"NUMBER":       1,
	"BOOLEAN":      2,
	"DATE_TIME":    3,
	"EMAIL":        4,
	"PHONE_NUMBER": 5,
	"URL":          6,
}

func (x CreateCustomFieldRequest_Type) String() string {
	return proto.EnumName(CreateCustomFieldRequest_Type_name, int32(x))
}
func (CreateCustomFieldRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_customfieldschema_6e8193972c6317ed, []int{0, 0}
}

type CustomField_Type int32

const (
	CustomField_TEXT         CustomField_Type = 0
	CustomField_NUMBER       CustomField_Type = 1
	CustomField_BOOLEAN      CustomField_Type = 2
	CustomField_DATE_TIME    CustomField_Type = 3
	CustomField_EMAIL        CustomField_Type = 4
	CustomField_PHONE_NUMBER CustomField_Type = 5
	CustomField_URL          CustomField_Type = 6
)

var CustomField_Type_name = map[int32]string{
	0: "TEXT",
	1: "NUMBER",
	2: "BOOLEAN",
	3: "DATE_TIME",
	4: "EMAIL",
	5: "PHONE_NUMBER",
	6: "URL",
}
var CustomField_Type_value = map[string]int32{
	"TEXT":         0,
	"NUMBER":       1,
	"BOOLEAN":      2,
	"DATE_TIME":    3,
	"EMAIL":        4,
	"PHONE_NUMBER": 5,
	"URL":          6,
}

func (x CustomField_Type) String() string {
	return proto.EnumName(CustomField_Type_name, int32(x))
}
func (CustomField_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_customfieldschema_6e8193972c6317ed, []int{5, 0}
}

type CreateCustomFieldRequest struct {
	Name                 string                        `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type                 CreateCustomFieldRequest_Type `protobuf:"varint,2,opt,name=type,enum=contactsapi.customfield.CreateCustomFieldRequest_Type" json:"type,omitempty"`
	Label                string                        `protobuf:"bytes,3,opt,name=label" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CreateCustomFieldRequest) Reset()         { *m = CreateCustomFieldRequest{} }
func (m *CreateCustomFieldRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCustomFieldRequest) ProtoMessage()    {}
func (*CreateCustomFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_customfieldschema_6e8193972c6317ed, []int{0}
}
func (m *CreateCustomFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomFieldRequest.Unmarshal(m, b)
}
func (m *CreateCustomFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomFieldRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCustomFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomFieldRequest.Merge(dst, src)
}
func (m *CreateCustomFieldRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCustomFieldRequest.Size(m)
}
func (m *CreateCustomFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomFieldRequest proto.InternalMessageInfo

func (m *CreateCustomFieldRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCustomFieldRequest) GetType() CreateCustomFieldRequest_Type {
	if m != nil {
		return m.Type
	}
	return CreateCustomFieldRequest_TEXT
}

func (m *CreateCustomFieldRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type ListCustomFieldsRequest struct {
	PageToken            string   `protobuf:"bytes,1,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	FieldMask            []string `protobuf:"bytes,3,rep,name=field_mask,json=fieldMask" json:"field_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCustomFieldsRequest) Reset()         { *m = ListCustomFieldsRequest{} }
func (m *ListCustomFieldsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCustomFieldsRequest) ProtoMessage()    {}
func (*ListCustomFieldsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_customfieldschema_6e8193972c6317ed, []int{1}
}
func (m *ListCustomFieldsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCustomFieldsRequest.Unmarshal(m, b)
}
func (m *ListCustomFieldsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCustomFieldsRequest.Marshal(b, m, deterministic)
}
func (dst *ListCustomFieldsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCustomFieldsRequest.Merge(dst, src)
}
func (m *ListCustomFieldsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCustomFieldsRequest.Size(m)
}
func (m *ListCustomFieldsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCustomFieldsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCustomFieldsRequest proto.InternalMessageInfo

func (m *ListCustomFieldsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListCustomFieldsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListCustomFieldsRequest) GetFieldMask() []string {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

type ListCustomFieldsResponse struct {
	CustomFields         []*CustomField `protobuf:"bytes,1,rep,name=custom_fields,json=customFields" json:"custom_fields,omitempty"`
	Count                int32          `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	NextPageToken        string         `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListCustomFieldsResponse) Reset()         { *m = ListCustomFieldsResponse{} }
func (m *ListCustomFieldsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCustomFieldsResponse) ProtoMessage()    {}
func (*ListCustomFieldsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_customfieldschema_6e8193972c6317ed, []int{2}
}
func (m *ListCustomFieldsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCustomFieldsResponse.Unmarshal(m, b)
}
func (m *ListCustomFieldsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCustomFieldsResponse.Marshal(b, m, deterministic)
}
func (dst *ListCustomFieldsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCustomFieldsResponse.Merge(dst, src)
}
func (m *ListCustomFieldsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCustomFieldsResponse.Size(m)
}
func (m *ListCustomFieldsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCustomFieldsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCustomFieldsResponse proto.InternalMessageInfo

func (m *ListCustomFieldsResponse) GetCustomFields() []*CustomField {
	if m != nil {
		return m.CustomFields
	}
	return nil
}

func (m *ListCustomFieldsResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListCustomFieldsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetCustomFieldRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	FieldMask            []string `protobuf:"bytes,2,rep,name=field_mask,json=fieldMask" json:"field_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomFieldRequest) Reset()         { *m = GetCustomFieldRequest{} }
func (m *GetCustomFieldRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomFieldRequest) ProtoMessage()    {}
func (*GetCustomFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_customfieldschema_6e8193972c6317ed, []int{3}
}
func (m *GetCustomFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomFieldRequest.Unmarshal(m, b)
}
func (m *GetCustomFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomFieldRequest.Marshal(b, m, deterministic)
}
func (dst *GetCustomFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomFieldRequest.Merge(dst, src)
}
func (m *GetCustomFieldRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomFieldRequest.Size(m)
}
func (m *GetCustomFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomFieldRequest proto.InternalMessageInfo

func (m *GetCustomFieldRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetCustomFieldRequest) GetFieldMask() []string {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

// TODO: Will we allow updating type/label?
type UpdateCustomFieldRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	UpdateMask           []string `protobuf:"bytes,3,rep,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCustomFieldRequest) Reset()         { *m = UpdateCustomFieldRequest{} }
func (m *UpdateCustomFieldRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCustomFieldRequest) ProtoMessage()    {}
func (*UpdateCustomFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_customfieldschema_6e8193972c6317ed, []int{4}
}
func (m *UpdateCustomFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCustomFieldRequest.Unmarshal(m, b)
}
func (m *UpdateCustomFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCustomFieldRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateCustomFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCustomFieldRequest.Merge(dst, src)
}
func (m *UpdateCustomFieldRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCustomFieldRequest.Size(m)
}
func (m *UpdateCustomFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCustomFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCustomFieldRequest proto.InternalMessageInfo

func (m *UpdateCustomFieldRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateCustomFieldRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateCustomFieldRequest) GetUpdateMask() []string {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type CustomField struct {
	Name  string           `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type  CustomField_Type `protobuf:"varint,2,opt,name=type,enum=contactsapi.customfield.CustomField_Type" json:"type,omitempty"`
	Label string           `protobuf:"bytes,3,opt,name=label" json:"label,omitempty"`
	Id    string           `protobuf:"bytes,4,opt,name=id" json:"id,omitempty"`
	// TODO: or Timestamp.proto?
	Created              string   `protobuf:"bytes,5,opt,name=created" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,6,opt,name=updated" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomField) Reset()         { *m = CustomField{} }
func (m *CustomField) String() string { return proto.CompactTextString(m) }
func (*CustomField) ProtoMessage()    {}
func (*CustomField) Descriptor() ([]byte, []int) {
	return fileDescriptor_customfieldschema_6e8193972c6317ed, []int{5}
}
func (m *CustomField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomField.Unmarshal(m, b)
}
func (m *CustomField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomField.Marshal(b, m, deterministic)
}
func (dst *CustomField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomField.Merge(dst, src)
}
func (m *CustomField) XXX_Size() int {
	return xxx_messageInfo_CustomField.Size(m)
}
func (m *CustomField) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomField.DiscardUnknown(m)
}

var xxx_messageInfo_CustomField proto.InternalMessageInfo

func (m *CustomField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomField) GetType() CustomField_Type {
	if m != nil {
		return m.Type
	}
	return CustomField_TEXT
}

func (m *CustomField) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *CustomField) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CustomField) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *CustomField) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateCustomFieldRequest)(nil), "contactsapi.customfield.CreateCustomFieldRequest")
	proto.RegisterType((*ListCustomFieldsRequest)(nil), "contactsapi.customfield.ListCustomFieldsRequest")
	proto.RegisterType((*ListCustomFieldsResponse)(nil), "contactsapi.customfield.ListCustomFieldsResponse")
	proto.RegisterType((*GetCustomFieldRequest)(nil), "contactsapi.customfield.GetCustomFieldRequest")
	proto.RegisterType((*UpdateCustomFieldRequest)(nil), "contactsapi.customfield.UpdateCustomFieldRequest")
	proto.RegisterType((*CustomField)(nil), "contactsapi.customfield.CustomField")
	proto.RegisterEnum("contactsapi.customfield.CreateCustomFieldRequest_Type", CreateCustomFieldRequest_Type_name, CreateCustomFieldRequest_Type_value)
	proto.RegisterEnum("contactsapi.customfield.CustomField_Type", CustomField_Type_name, CustomField_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomFieldServiceClient is the client API for CustomFieldService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomFieldServiceClient interface {
	CreateCustomField(ctx context.Context, in *CreateCustomFieldRequest, opts ...grpc.CallOption) (*CustomField, error)
	ListCustomFields(ctx context.Context, in *ListCustomFieldsRequest, opts ...grpc.CallOption) (*ListCustomFieldsResponse, error)
	GetCustomField(ctx context.Context, in *GetCustomFieldRequest, opts ...grpc.CallOption) (*CustomField, error)
	UpdateCustomField(ctx context.Context, in *UpdateCustomFieldRequest, opts ...grpc.CallOption) (*CustomField, error)
}

type customFieldServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomFieldServiceClient(cc *grpc.ClientConn) CustomFieldServiceClient {
	return &customFieldServiceClient{cc}
}

func (c *customFieldServiceClient) CreateCustomField(ctx context.Context, in *CreateCustomFieldRequest, opts ...grpc.CallOption) (*CustomField, error) {
	out := new(CustomField)
	err := c.cc.Invoke(ctx, "/contactsapi.customfield.CustomFieldService/CreateCustomField", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customFieldServiceClient) ListCustomFields(ctx context.Context, in *ListCustomFieldsRequest, opts ...grpc.CallOption) (*ListCustomFieldsResponse, error) {
	out := new(ListCustomFieldsResponse)
	err := c.cc.Invoke(ctx, "/contactsapi.customfield.CustomFieldService/ListCustomFields", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customFieldServiceClient) GetCustomField(ctx context.Context, in *GetCustomFieldRequest, opts ...grpc.CallOption) (*CustomField, error) {
	out := new(CustomField)
	err := c.cc.Invoke(ctx, "/contactsapi.customfield.CustomFieldService/GetCustomField", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customFieldServiceClient) UpdateCustomField(ctx context.Context, in *UpdateCustomFieldRequest, opts ...grpc.CallOption) (*CustomField, error) {
	out := new(CustomField)
	err := c.cc.Invoke(ctx, "/contactsapi.customfield.CustomFieldService/UpdateCustomField", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomFieldServiceServer is the server API for CustomFieldService service.
type CustomFieldServiceServer interface {
	CreateCustomField(context.Context, *CreateCustomFieldRequest) (*CustomField, error)
	ListCustomFields(context.Context, *ListCustomFieldsRequest) (*ListCustomFieldsResponse, error)
	GetCustomField(context.Context, *GetCustomFieldRequest) (*CustomField, error)
	UpdateCustomField(context.Context, *UpdateCustomFieldRequest) (*CustomField, error)
}

func RegisterCustomFieldServiceServer(s *grpc.Server, srv CustomFieldServiceServer) {
	s.RegisterService(&_CustomFieldService_serviceDesc, srv)
}

func _CustomFieldService_CreateCustomField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomFieldServiceServer).CreateCustomField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contactsapi.customfield.CustomFieldService/CreateCustomField",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomFieldServiceServer).CreateCustomField(ctx, req.(*CreateCustomFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomFieldService_ListCustomFields_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCustomFieldsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomFieldServiceServer).ListCustomFields(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contactsapi.customfield.CustomFieldService/ListCustomFields",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomFieldServiceServer).ListCustomFields(ctx, req.(*ListCustomFieldsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomFieldService_GetCustomField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomFieldServiceServer).GetCustomField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contactsapi.customfield.CustomFieldService/GetCustomField",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomFieldServiceServer).GetCustomField(ctx, req.(*GetCustomFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomFieldService_UpdateCustomField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCustomFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomFieldServiceServer).UpdateCustomField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contactsapi.customfield.CustomFieldService/UpdateCustomField",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomFieldServiceServer).UpdateCustomField(ctx, req.(*UpdateCustomFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomFieldService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "contactsapi.customfield.CustomFieldService",
	HandlerType: (*CustomFieldServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomField",
			Handler:    _CustomFieldService_CreateCustomField_Handler,
		},
		{
			MethodName: "ListCustomFields",
			Handler:    _CustomFieldService_ListCustomFields_Handler,
		},
		{
			MethodName: "GetCustomField",
			Handler:    _CustomFieldService_GetCustomField_Handler,
		},
		{
			MethodName: "UpdateCustomField",
			Handler:    _CustomFieldService_UpdateCustomField_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/main/proto/contactsapi/customfieldschema.proto",
}

func init() {
	proto.RegisterFile("src/main/proto/contactsapi/customfieldschema.proto", fileDescriptor_customfieldschema_6e8193972c6317ed)
}

var fileDescriptor_customfieldschema_6e8193972c6317ed = []byte{
	// 644 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0xfd, 0xd6, 0x71, 0xd2, 0x66, 0xd2, 0xf6, 0x73, 0x47, 0x54, 0x5d, 0xb5, 0x54, 0x44, 0x16,
	0x42, 0x85, 0x43, 0x4c, 0x83, 0xc4, 0x01, 0x89, 0x43, 0x5b, 0x5c, 0x28, 0x4a, 0xda, 0x2a, 0x75,
	0x25, 0x4e, 0x58, 0x5b, 0x7b, 0x29, 0x56, 0x13, 0xdb, 0x64, 0x37, 0x15, 0x2d, 0xe2, 0x82, 0xc4,
	0x01, 0x71, 0x42, 0xdc, 0xb8, 0xf2, 0x6f, 0xb8, 0xf2, 0x17, 0xf8, 0x01, 0xfc, 0x04, 0xe4, 0xb5,
	0x83, 0xdc, 0x24, 0x86, 0xe6, 0xc0, 0x2d, 0x33, 0xde, 0x37, 0xfb, 0xe6, 0xf9, 0xbd, 0x18, 0x9a,
	0xa2, 0xef, 0x59, 0x3d, 0x16, 0x84, 0x56, 0xdc, 0x8f, 0x64, 0x64, 0x79, 0x51, 0x28, 0x99, 0x27,
	0x05, 0x8b, 0x03, 0xcb, 0x1b, 0x08, 0x19, 0xf5, 0x5e, 0x04, 0xbc, 0xeb, 0x0b, 0xef, 0x25, 0xef,
	0xb1, 0x86, 0x3a, 0x83, 0xcb, 0xb9, 0x43, 0x8d, 0xdc, 0xa1, 0x95, 0xeb, 0x27, 0x51, 0x74, 0xd2,
	0xe5, 0x56, 0x02, 0x66, 0x61, 0x18, 0x49, 0x26, 0x83, 0x28, 0x14, 0x29, 0xcc, 0xfc, 0x49, 0x80,
	0x6e, 0xf7, 0x39, 0x93, 0x7c, 0x5b, 0x61, 0x76, 0x12, 0x4c, 0x87, 0xbf, 0x1a, 0x70, 0x21, 0x11,
	0x41, 0x0f, 0x59, 0x8f, 0x53, 0x52, 0x27, 0xeb, 0xd5, 0x8e, 0xfa, 0x8d, 0x4f, 0x41, 0x97, 0xe7,
	0x31, 0xa7, 0x5a, 0x9d, 0xac, 0x2f, 0x34, 0xef, 0x37, 0x0a, 0xae, 0x6d, 0x14, 0x0d, 0x6d, 0x38,
	0xe7, 0x31, 0xef, 0xa8, 0x19, 0x78, 0x0d, 0xca, 0x5d, 0x76, 0xcc, 0xbb, 0xb4, 0xa4, 0x2e, 0x48,
	0x0b, 0xf3, 0x39, 0xe8, 0xc9, 0x19, 0x9c, 0x05, 0xdd, 0xb1, 0x9f, 0x39, 0xc6, 0x7f, 0x08, 0x50,
	0xd9, 0x3b, 0x6a, 0x6f, 0xd9, 0x1d, 0x83, 0x60, 0x0d, 0x66, 0xb6, 0xf6, 0xf7, 0x5b, 0xf6, 0xe6,
	0x9e, 0xa1, 0xe1, 0x3c, 0x54, 0x1f, 0x6d, 0x3a, 0xb6, 0xeb, 0xec, 0xb6, 0x6d, 0xa3, 0x84, 0x55,
	0x28, 0xdb, 0xed, 0xcd, 0xdd, 0x96, 0xa1, 0xa3, 0x01, 0x73, 0x07, 0x4f, 0xf6, 0xf7, 0x6c, 0x37,
	0x03, 0x96, 0x71, 0x06, 0x4a, 0x47, 0x9d, 0x96, 0x51, 0x31, 0x25, 0x2c, 0xb7, 0x02, 0x21, 0x73,
	0xd4, 0xc4, 0x70, 0xe1, 0x35, 0x80, 0x98, 0x9d, 0x70, 0x57, 0x46, 0xa7, 0x3c, 0xcc, 0xd6, 0xae,
	0x26, 0x1d, 0x27, 0x69, 0xe0, 0x2a, 0xa8, 0xc2, 0x15, 0xc1, 0x45, 0x2a, 0x40, 0xb9, 0x33, 0x9b,
	0x34, 0x0e, 0x83, 0x0b, 0x9e, 0x60, 0xd5, 0xe6, 0x6e, 0x8f, 0x89, 0x53, 0x5a, 0xaa, 0x97, 0x12,
	0xac, 0xea, 0xb4, 0x99, 0x38, 0x35, 0xbf, 0x12, 0xa0, 0xe3, 0xd7, 0x8a, 0x38, 0x0a, 0x05, 0xc7,
	0x5d, 0x98, 0x4f, 0xb5, 0x73, 0xd3, 0x17, 0x4b, 0x49, 0xbd, 0xb4, 0x5e, 0x6b, 0xde, 0x2c, 0x56,
	0x37, 0xa7, 0xeb, 0x9c, 0x97, 0x1b, 0x99, 0x68, 0xea, 0x45, 0x83, 0x50, 0x66, 0xfc, 0xd2, 0x02,
	0x6f, 0xc1, 0xff, 0x21, 0x7f, 0x2d, 0xdd, 0xdc, 0x76, 0xa9, 0xe6, 0xf3, 0x49, 0xfb, 0x60, 0xb8,
	0xa1, 0xb9, 0x03, 0x4b, 0x8f, 0xb9, 0x9c, 0x60, 0x85, 0x05, 0xd0, 0x02, 0x3f, 0x53, 0x44, 0x0b,
	0xfc, 0x91, 0x6d, 0xb5, 0xd1, 0x6d, 0x5d, 0xa0, 0x47, 0xb1, 0x3f, 0xd9, 0x55, 0xa3, 0xa3, 0x86,
	0x2e, 0xd3, 0x72, 0x2e, 0xbb, 0x01, 0xb5, 0x81, 0xc2, 0xe7, 0xd5, 0x84, 0xb4, 0xa5, 0x2e, 0xf8,
	0xa2, 0x41, 0x2d, 0x37, 0x7b, 0xa2, 0x55, 0x1f, 0x5e, 0xb2, 0xea, 0xed, 0xab, 0x88, 0xf9, 0x57,
	0x77, 0x66, 0xec, 0xf5, 0xdf, 0xec, 0x29, 0xcc, 0x78, 0xca, 0xea, 0x3e, 0x2d, 0xab, 0xe6, 0xb0,
	0x4c, 0x9e, 0xa4, 0x84, 0x7d, 0x5a, 0x49, 0x9f, 0x64, 0xe5, 0xbf, 0x76, 0x78, 0xf3, 0x9b, 0x0e,
	0x98, 0x5b, 0xea, 0x90, 0xf7, 0xcf, 0x02, 0x8f, 0xe3, 0x07, 0x02, 0x8b, 0x63, 0xb1, 0xc4, 0x8d,
	0xa9, 0x23, 0xbc, 0x72, 0x25, 0x5f, 0x9a, 0xab, 0xef, 0xbe, 0xff, 0xf8, 0xac, 0x2d, 0x99, 0x86,
	0x75, 0xb6, 0x71, 0xe9, 0x6f, 0xeb, 0x01, 0xb9, 0x83, 0x9f, 0x08, 0x18, 0xa3, 0x71, 0xc0, 0xbb,
	0x85, 0x73, 0x0b, 0x02, 0xbb, 0xb2, 0x31, 0x05, 0x22, 0xcd, 0x9a, 0x49, 0x15, 0x2d, 0xc4, 0x31,
	0x5a, 0xf8, 0x9e, 0xc0, 0xc2, 0x65, 0xf7, 0x63, 0xa3, 0x70, 0xfe, 0xc4, 0x98, 0x5c, 0x51, 0x99,
	0x35, 0x45, 0x61, 0x19, 0x97, 0x46, 0x29, 0x58, 0x6f, 0x02, 0xff, 0x2d, 0x7e, 0x24, 0xb0, 0x38,
	0x96, 0x9e, 0x3f, 0xbc, 0xa7, 0xa2, 0xa4, 0x4d, 0xc7, 0xa6, 0x39, 0x99, 0xcd, 0x96, 0x76, 0x40,
	0x8e, 0x2b, 0xea, 0x63, 0x71, 0xef, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x2d, 0x29, 0xfa,
	0x99, 0x06, 0x00, 0x00,
}
